
Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: 'Your.Package:Default.Document'
        suffix: .Document
Neos:
  Neos:
    typoScript:
      autoInclude:
        Ttree.Fusion.DocumentFinder: true
