
Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: 'Neos.Neos:Page'
        suffix: .Document

Neos:
  Neos:
    fusion:
      autoInclude:
        Ttree.Fusion.DocumentFinder: true
