
Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: 'Your.Package:Default.Document'
        suffix: .Document

Neos:
  Neos:
    fusion:
      autoInclude:
        Ttree.Fusion.DocumentFinder: true
